rabbitmq:
  enabled: true
  username: rabbitadmin
  password: rabbitpassword
  port: 5672
  uiPort: 15672   
  orderreq:
    queueName: reqorders
    exchangeName: reqordersexchange
  orderres:
    queueName: resorders
    exchangeName: resordersexchange
  confirmreq:
    paymentQueueName: reqpaymentconfirms
    storeQueueName: reqstoreconfirms	
    deliveryQueueName: reqdeliveryconfirms
    exchangeName: reqconfirmexchange
  confirmres:
    queueName: resconfirms
    exchangeName: resconfirmexchange

    