delivery:
  name: delivery
  postgres:
    appUsername: otususer
    appPassword: otususer
    appDatabase: otusdb
    appDbUrl: jdbc:postgresql://postgres-service:5432/delivery_db
  rabbitmq:
    username: rabbitadmin
    password: rabbitpassword
  service:
    port: 8080
    type: ClusterIP
