apiVersion: v1
kind: Service
metadata:
  name: {{ include "store.fullname" . }}-service
spec:
  selector:
    app: {{ include "store.fullname" . }}
  ports:
    - protocol: TCP
      name: web
      port: {{.Values.store.service.port}}
      targetPort: {{.Values.store.service.port}} 
  type: {{.Values.store.service.type}} 
